### ISSUE TITLE
[SUGGESTION] Dictionary

### ISSUE THREAD

**Issue by wcaleniekubaa** [ItsMeFrenzy/Reaper#1]
Dictionary stored in other file
to create the mappings

like:
dictionary file:
abc

how much letters: 4
how much lines (idk): 2

mapping file:

bcab
abac

**Comment by ItsMeFrenzy** [comment]
I am definitely open to adding a dictionary, for the moment though, it's more common to use I's and L's.

I will definitely revisit this later on.
